name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: pre.tex
          latexmk_use_xelatex: true
          extra_fonts: ./font/*.ttc
      - name: Commit PDF file
        uses: stefanzweifel/git-auto-commit-action@v4